//
//  LBRGreekTypes.h
//  VerbiGreciMacOSX
//
//  Created by Claudio Capobianco on 05/05/12.
//  Copyright (c) 2012 Librum. All rights reserved.
//

#ifndef VerbiGreciMacOSX_LBRGreekTypes_h
#define VerbiGreciMacOSX_LBRGreekTypes_h

typedef enum LBRLetterSign {
    LBR_LETTER_SIGN_NONE = 0,
    LBR_LETTER_SIGN_PSILI,
    LBR_LETTER_SIGN_DASIA,
    LBR_LETTER_SIGN_VARIA,
    LBR_LETTER_SIGN_OXIA,
    LBR_LETTER_SIGN_PERISPOMENI,
    LBR_LETTER_SIGN_YPOGERGRAMMENI,
    
    LBR_LETTER_SIGN_PSILI_VARIA,
    LBR_LETTER_SIGN_DASIA_VARIA,
    LBR_LETTER_SIGN_PSILI_OXIA,
    LBR_LETTER_SIGN_DASIA_OXIA,
    LBR_LETTER_SIGN_PSILI_PERISPOMENI,
    LBR_LETTER_SIGN_DASIA_PERISPOMENI,
    
    LBR_LETTER_SIGN_PSILI_YPOGERGRAMMENI,
    LBR_LETTER_SIGN_DASIA_YPOGERGRAMMENI,
    LBR_LETTER_SIGN_VARIA_YPOGERGRAMMENI,
    LBR_LETTER_SIGN_OXIA_YPOGERGRAMMENI,
    LBR_LETTER_SIGN_PERISPOMENI_YPOGERGRAMMENI,
    LBR_LETTER_SIGN_SPARE,
    
    LBR_LETTER_SIGN_PSILI_VARIA_YPOGERGRAMMENI,
    LBR_LETTER_SIGN_DASIA_VARIA_YPOGERGRAMMENI,
    LBR_LETTER_SIGN_PSILI_OXIA_YPOGERGRAMMENI,
    LBR_LETTER_SIGN_DASIA_OXIA_YPOGERGRAMMENI,
    LBR_LETTER_SIGN_PSILI_PERISPOMENI_YPOGERGRAMMENI,
    LBR_LETTER_SIGN_DASIA_PERISPOMENI_YPOGERGRAMMENI,
    
    LBR_LETTER_SIGN_VRACHY,
    LBR_LETTER_SIGN_MACRON,
    LBR_LETTER_SIGN_MACRON_OXIA,
    LBR_LETTER_SIGN_MACRON_PSILI,
    LBR_LETTER_SIGN_MACRON_DASIA,
    LBR_LETTER_SIGN_VRACHY_OXIA,
    
    LBR_LETTER_SIGN_NUM
}LBRLetterSign; 

#endif
